/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gean.tttemplate.view.tweetEmMassaImport;

import com.gean.tttemplate.utils.AlertFactory;
import com.gean.tttemplate.utils.Param;
import com.gean.tttemplate.utils.TweetPreset;
import com.gean.tttemplate.utils.TweetPresetFactory;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutionException;
import java.util.function.Consumer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Button;
import javafx.stage.FileChooser;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;

/**
 *
 * @author GeanCarneiro
 */
public class TweetEmMassaImportView extends javax.swing.JDialog {
    
    private static File file = null;
    
    private TweetPreset preset;
    
    private SwingWorker<File, Void> importarWorker = null;
    
    /**
     * Creates new form TweetEmMassaImportView
     * @param parent
     */
    public TweetEmMassaImportView(java.awt.Frame parent, TweetPreset preset) {
        super(parent, true);
        this.preset = preset;
        initComponents();
        
        this.pack();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelForm = new javax.swing.JPanel();
        lblAriquivo = new javax.swing.JLabel();
        txtNomeArquivo = new javax.swing.JTextField();
        btnAbrirArquivo = new javax.swing.JButton();
        btnGerarModelo = new javax.swing.JButton();
        panelBotoes = new javax.swing.JPanel();
        btnImportar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tweet Em Massa");

        lblTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Tweet Em Massa");

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel1.setText(this.preset.getNome());

        lblAriquivo.setText("Importar do Arq.:");
        panelForm.add(lblAriquivo);

        txtNomeArquivo.setEditable(false);
        txtNomeArquivo.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeArquivo.setColumns(20);
        panelForm.add(txtNomeArquivo);

        btnAbrirArquivo.setText("Navegar");
        btnAbrirArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirArquivoActionPerformed(evt);
            }
        });
        panelForm.add(btnAbrirArquivo);

        btnGerarModelo.setText("Gerar Modelo");
        btnGerarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarModeloActionPerformed(evt);
            }
        });
        panelForm.add(btnGerarModelo);

        panelBotoes.setLayout(new java.awt.GridBagLayout());

        btnImportar.setText("Importar");
        btnImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 0.1;
        panelBotoes.add(btnImportar, gridBagConstraints);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 0.1;
        panelBotoes.add(btnCancelar, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirArquivoActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Carregar Modelo");
        chooser.setMultiSelectionEnabled(false);
        chooser.setFileFilter(new FileNameExtensionFilter("Arquivo xls", "*.xls"));
        chooser.setAcceptAllFileFilterUsed(false);
        
        if(chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            file = chooser.getSelectedFile();
            txtNomeArquivo.setText(file == null ? "" : file.getAbsolutePath());
        }
        
    }//GEN-LAST:event_btnAbrirArquivoActionPerformed

    private void btnImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnImportarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        file = null;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGerarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarModeloActionPerformed
        if (this.importarWorker == null) {
            this.importarWorker = new SwingWorker<File, Void>() {
                @Override
                protected File doInBackground() throws Exception {
                    JFileChooser chooser = new JFileChooser();
                    chooser.setDialogTitle("Salvar Modelo Gerado");
                    chooser.setSelectedFile(new File("modelo_preset.xls"));
                    chooser.setFileFilter(new FileNameExtensionFilter("Arquivo xls", "*.xls"));
                    chooser.setMultiSelectionEnabled(false);
                    final int[] opt = new int[1];
                    
                    SwingUtilities.invokeAndWait(() -> opt[0] = chooser.showSaveDialog(null));
                    
                    if(opt[0] == JFileChooser.APPROVE_OPTION){
                        File outputFile = chooser.getSelectedFile();
                        if(!outputFile.getName().endsWith(".xls"))
                            outputFile = new File(outputFile.getAbsolutePath() + ".xls");
                        
                        outputFile.createNewFile();
                        
                        List<Param> params = TweetPresetFactory.getParams(preset.getPreset());
                        
                        try(Workbook wb = new HSSFWorkbook(); FileOutputStream fos = new FileOutputStream(outputFile)) {
                            Sheet planilha = wb.createSheet(preset.getNome());

                            Row row = planilha.createRow(0);
                            row.setHeight((short) 300);
                            int colIndex = 0;
                            for(Param p: params) {
                                    row.createCell(colIndex).setCellValue(p.getLabel());
                                    planilha.autoSizeColumn(colIndex);
                                    colIndex++;
                            }

                            if(preset.getMidia()) {
                                    row.createCell(colIndex).setCellValue(TweetPresetFactory.DEFAULT_MIDIA_LABEL);
                                    planilha.autoSizeColumn(colIndex);
                            }

                            wb.write(fos);

                        }
                        
                        
                    }
                    return null;
                }

                @Override
                protected void done() {
                    super.done();
                    
                    try {
                        File file = get();
                        AlertFactory.createInformationAlert("ARQUIVO " + file.getName().toUpperCase() + " CRIADO COM SUCESSO!!");
                    } catch (Exception e) {
                        Logger.getLogger(TweetEmMassaImportView.class.getName()).log(Level.SEVERE, null, e);
                        e.printStackTrace();
                        AlertFactory.createErrorAlert("Erro ao gerar modelo: " + e.getLocalizedMessage());
                        return;
                    }finally {
                        importarWorker = null;
                    }
                
                }
                
                
            };
            this.importarWorker.execute();
            
            
            
        }
        
        
    }//GEN-LAST:event_btnGerarModeloActionPerformed
       
    public static File showDialog(java.awt.Frame frame, TweetPreset preset) {
        TweetEmMassaImportView dialog = new TweetEmMassaImportView(frame, preset);
                
        return TweetEmMassaImportView.file;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirArquivo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGerarModelo;
    private javax.swing.JButton btnImportar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAriquivo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelForm;
    private javax.swing.JTextField txtNomeArquivo;
    // End of variables declaration//GEN-END:variables
}
